"""create user_game_entries table

Revision ID: 1fe0ead60839
Revises: b69b1d8cafb0
Create Date: 2026-07-17 17:20:45.169284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1fe0ead60839'
down_revision = 'b69b1d8cafb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_game_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('hours_played', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('replay_count', sa.Integer(), nullable=False),
    sa.Column('platform_played', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('backlog', 'playing', 'completed', 'dropped', 'replaying')", name='ck_user_game_entries_status'),
    sa.CheckConstraint('rating IS NULL OR (rating >= 1 AND rating <= 10)', name='ck_user_game_entries_rating'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_id', name='uq_user_game_entries_user_game')
    )
    with op.batch_alter_table('user_game_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_game_entries_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_game_entries_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_game_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_game_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_game_entries_game_id'))

    op.drop_table('user_game_entries')
    # ### end Alembic commands ###
