"""create follows table

Revision ID: 45e2e68c8ef4
Revises: 9e88e609dd33
Create Date: 2026-07-20 19:14:55.388156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e2e68c8ef4'
down_revision = '9e88e609dd33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('follower_id != followed_id', name='ck_follows_no_self_follow'),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'followed_id', name='uq_follows_follower_followed')
    )
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_follows_followed_id'), ['followed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follows_follower_id'), ['follower_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follows_follower_id'))
        batch_op.drop_index(batch_op.f('ix_follows_followed_id'))

    op.drop_table('follows')
    # ### end Alembic commands ###
