"""create game feedback table

Revision ID: 60a3ed39a593
Revises: cf9ee869c48f
Create Date: 2026-07-22 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60a3ed39a593'
down_revision = 'cf9ee869c48f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("sentiment IN ('liked', 'disliked')", name='ck_game_feedback_sentiment'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_id', name='uq_game_feedback_user_game')
    )
    with op.batch_alter_table('game_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_feedback_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_feedback_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_feedback_user_id'))
        batch_op.drop_index(batch_op.f('ix_game_feedback_game_id'))

    op.drop_table('game_feedback')
    # ### end Alembic commands ###
